src/Entity/Bande.php
<?php

namespace App\Entity;

use App\Repository\BandeRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use IntlDateFormatter;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BandeRepository::class)]
class Bande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\PositiveOrZero]
    #[ORM\Column]
    private ?int $nb_poussins = null;

    #[Assert\NotNull]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $date_debut = null;

    #[Assert\PositiveOrZero]
    #[ORM\Column]
    private int $nb_mortalite = 0;

    #[ORM\OneToMany(mappedBy: 'bande', targetEntity: Depense::class, orphanRemoval: true)]
    #[ORM\OrderBy(['created_at' => 'DESC'])]
    private Collection $depenses;

    #[ORM\OneToMany(mappedBy: 'bande', targetEntity: Vente::class, orphanRemoval: true)]
    #[ORM\OrderBy(['created_at' => 'DESC'])]
    private Collection $ventes;

    #[Assert\GreaterThan(
        propertyPath: 'date_debut',
        message: "La date de cloture doit être supérieure à la date de début."
    )]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $date_cloture = null;

    public function __construct()
    {
        $this->depenses = new ArrayCollection();
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbPoussins(): ?int
    {
        return $this->nb_poussins;
    }

    public function setNbPoussins(int $nb_poussins): self
    {
        $this->nb_poussins = $nb_poussins;

        return $this;
    }

    public function getNbMortalite(): int
    {
        return $this->nb_mortalite;
    }

    public function setNbMortalite(int $nb_mortalite): self
    {
        $this->nb_mortalite = $nb_mortalite;

        return $this;
    }

    public function getNbJours(): ?int
    {
        if ($this->isClotured()) {
            return date_diff($this->getDateCloture(), $this->getDateDebut())->days;
        }
        return date_diff(new DateTime(), $this->getDateDebut())->days;
    }

    public function isClotured(): bool
    {
        return $this->date_cloture !== null;
    }

    public function getDateCloture(): ?DateTimeInterface
    {
        return $this->date_cloture;
    }

    public function setDateCloture(?DateTimeInterface $date_cloture): self
    {
        $this->date_cloture = $date_cloture;

        return $this;
    }

    public function getDateDebut(): ?DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    /**
     * @return Collection<int, Depense>
     */
    public function getDepenses(): Collection
    {
        return $this->depenses;
    }

    public function addDepense(Depense $depense): self
    {
        if (!$this->depenses->contains($depense)) {
            $this->depenses->add($depense);
            $depense->setBande($this);
        }

        return $this;
    }

    public function removeDepense(Depense $depense): self
    {
        if ($this->depenses->removeElement($depense)) {
            // set the owning side to null (unless already changed)
            if ($depense->getBande() === $this) {
                $depense->setBande(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Vente>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): self
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setBande($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): self
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getBande() === $this) {
                $vente->setBande(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        $formatter = new IntlDateFormatter('fr_FR', IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);
        $date = $formatter->format($this->getDateDebut());
        return "Bande {$this->nb_poussins} du $date";
    }
}

src/Entity/Vente.php
<?php

namespace App\Entity;

use App\Repository\VenteRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VenteRepository::class)]
class Vente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'ventes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Bande $bande = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $client = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getBande(): ?Bande
    {
        return $this->bande;
    }

    public function setBande(?Bande $bande): self
    {
        $this->bande = $bande;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/BandeType.php
<?php

namespace App\Form;

use App\Entity\Bande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nb_poussins', null, [
                'label' => 'Nombre de poussins'
            ])
            ->add('date_debut', DateType::class, [
                'label' => 'Date démarrage',
                'widget' => 'single_text',
            ])
            ->add('nb_mortalite', null, [
                'label' => 'Mortalités'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Bande::class,
        ]);
    }
}

src/Controller/BandeController.php
<?php

namespace App\Controller;

use App\Entity\Bande;
use App\Entity\Depense;
use App\Entity\Vente;
use App\Form\BandeType;
use App\Form\DepenseType;
use App\Form\VenteType;
use App\Repository\BandeRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/bande')]
class BandeController extends AbstractController
{
    #[Route('/', name: 'app_bande_index', methods: ['GET'])]
    public function index(BandeRepository $bandeRepository): Response
    {
        ['all' => $all, 'open' => $open, 'close' => $close] = $bandeRepository->getBandes();
        return $this->render('bande/index.html.twig', [
            'bandes' => $open,
            'bandesCloture' => $close,
            'soldeCloture' => $bandeRepository->soldeCloture($close),
            'soldeCurrent' => $bandeRepository->soldeCurrent($all),
        ]);
    }

    #[Route('/new', name: 'app_bande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BandeRepository $bandeRepository): Response
    {
        $bande = new Bande();
        $bande->setDateDebut(new DateTime());
        $bande->setNbMortalite(0);
        $form = $this->createForm(BandeType::class, $bande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bandeRepository->save($bande, true);

            return $this->redirectToRoute('app_bande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bande/new.html.twig', [
            'bande' => $bande,
            'formBande' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_bande_show', methods: ['GET'])]
    public function show(Bande $bande, BandeRepository $bandeRepository): Response
    {
        // Form bande
        $formBande = $this->createForm(BandeType::class, $bande, ['action' => $this->generateUrl('app_bande_edit', ['id' => $bande->getId()])]);
        // Form depense
        $depense = new Depense();
        $depense->setCreatedAt(new DateTime());
        $depense->setBande($bande);
        $formDepense = $this->createForm(DepenseType::class, $depense, ['action' => $this->generateUrl('app_depense_new')]);
        // Form vente
        $vente = new Vente();
        $vente->setCreatedAt(new DateTime());
        $vente->setBande($bande);
        $formVente = $this->createForm(VenteType::class, $vente, ['action' => $this->generateUrl('app_vente_new')]);

        return $this->render('bande/show.html.twig', [
            'bande' => $bande,
            'totalDepense' => $bandeRepository->totalDepense($bande),
            'totalVente' => $bandeRepository->totalVente($bande),
            'stock' => $bandeRepository->stock($bande),
            'bilan' => $bandeRepository->bilan($bande),
            'formBande' => $formBande,
            'formDepense' => $formDepense,
            'formVente' => $formVente,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_bande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Bande $bande, BandeRepository $bandeRepository): Response
    {
        $form = $this->createForm(BandeType::class, $bande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bandeRepository->save($bande, true);

            return $this->redirectToRoute('app_bande_show', ['id' => $bande->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bande/edit.html.twig', [
            'bande' => $bande,
            'formBande' => $form,
        ]);
    }

    #[Route('/{id}/cloture', name: 'app_bande_cloture', methods: ['GET', 'POST'])]
    public function cloture(Request $request, Bande $bande, BandeRepository $bandeRepository): Response
    {
        $form = $this->createFormBuilder($bande, ['attr' => ['onsubmit' => 'return handleForm(event);']])
            ->setAction($this->generateUrl('app_bande_cloture', ['id' => $bande->getId()]))
            ->add('date_cloture', DateType::class, [
                'label' => 'Date cloture',
                'widget' => 'single_text',
            ])
            ->add('save', SubmitType::class, ['label' => 'Cloturer la bande'])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bandeRepository->save($bande, true);

            return $this->redirectToRoute('app_bande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bande/_form-cloture.html.twig', [
            'bande' => $bande,
            'formBande' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_bande_delete', methods: ['POST'])]
    public function delete(Request $request, Bande $bande, BandeRepository $bandeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $bande->getId(), $request->request->get('_token'))) {
            $bandeRepository->remove($bande, true);
        }

        return $this->redirectToRoute('app_bande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/bande/_delete_form.html.twig
<form method="post" action="{{ path('app_bande_delete', {'id': bande.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bande.id) }}">
    <button class="btn" data-tooltip="Supprimer cette bande">Delete</button>
</form>

templates/bande/_form-cloture.html.twig
{{ form_start(formBande) }}
<table role="grid">
    <tbody>
    <tr>
        <td>Nombre de poussins</td>
        <td>{{ bande.nbPoussins }}</td>
    </tr>
    <tr>
        <td>Date démarrage</td>
        <td>{{ bande.dateDebut ? bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") : '' }}</td>
    </tr>
    <tr>
        <td>Mortalites</td>
        <td>{{ bande.nbMortalite }}</td>
    </tr>
    </tbody>
</table>
{{ form_widget(formBande) }}
{{ form_end(formBande) }}

templates/bande/_form.html.twig
{{ form_start(formBande) }}
    {{ form_widget(formBande) }}
<button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(formBande) }}

templates/bande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bande{% endblock %}

{% block body %}
    <article>
        <header>
            <h1>Editer les infos de la bande</h1>
        </header>

        {{ include('bande/_form.html.twig', {'button_label': 'Editer'}) }}

        <footer>
            <a href="{{ path('app_bande_index') }}">Retour à la liste des bandes</a>
            {{ include('bande/_delete_form.html.twig') }}
        </footer>
    </article>
{% endblock %}

templates/bande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bande index
{% endblock %}

{% block body %}

    <article>
        <header>
            <h2>Bandes en cours</h2>
            <a href="{{ path('app_bande_new') }}" data-tooltip="Demarrer une nouvelle bande">
                <i class="fa-solid fa-plus"></i>
            </a>
        </header>

        <figure>
            <table class="table" role="grid">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre de poussins</th>
                    <th>Date démarrage</th>
                    <th>Mortalites</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for bande in bandes %}
                    <tr>
                        <td>{{ bande.id }}</td>
                        <td>{{ bande.nbPoussins }}</td>
                        <td>{{ bande.dateDebut ? bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") : '' }}</td>
                        <td>{{ bande.nbMortalite }}</td>
                        <td class="actions">
                            <a href="{{ path('app_bande_show', {'id': bande.id}) }}" role="button" class="outline"
                               data-tooltip="Consulter les details de la bande">
                                <i class="fa-regular fa-eye"></i>
                            </a>
                            <a href="{{ path('app_bande_edit', {'id': bande.id}) }}" role="button" class="outline"
                               data-tooltip="Editer les infos de la bande">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a href="#" role="button" class="outline warning"
                               data-target="modal-cloture-bande-{{ bande.id }}"
                               data-path-content="{{ path('app_bande_cloture', {'id': bande.id}) }}"
                               data-tooltip="Cloturer la bande">
                                <i class="fa-regular fa-hourglass"></i>
                            </a>
                        </td>
                    </tr>
                    <!-- Modal -->
                    <dialog id="modal-cloture-bande-{{ bande.id }}">
                        <article>
                            <header>
                                <a href="#close" aria-label="Close" class="close"
                                   data-target="modal-cloture-bande-{{ bande.id }}"
                                   onclick="toggleModal(event)"></a>
                                <h3>Cloturer la bande du
                                    {{ bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}
                                    !</h3>
                            </header>
                            <div class="contentTarget"></div>
                        </article>
                    </dialog>
                {% else %}
                    <tr>
                        <td colspan="5">Pas de bandes actuellement</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </figure>
    </article>

    <article>
        <header><h2>Bandes cloturées</h2></header>

        <figure>
            <table class="table" role="grid">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre de poussins</th>
                    <th>Date démarrage</th>
                    <th>Date de cloture</th>
                    <th>Mortalites</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for bande in bandesCloture %}
                    <tr>
                        <td>{{ bande.id }}</td>
                        <td>{{ bande.nbPoussins }}</td>
                        <td>{{ bande.dateDebut ? bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") : '' }}</td>
                        <td>{{ bande.dateDebut ? bande.dateCloture|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") : '' }}</td>
                        <td>{{ bande.nbMortalite }}</td>
                        <td class="actions">
                            <a href="{{ path('app_bande_show', {'id': bande.id}) }}" role="button" class="outline">
                                <i class="fa-regular fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Pas de bandes cloturées actuellement</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </figure>
    </article>

    <article>
        <header><h2>Compte</h2></header>
        <figure>
            <table>
                <tbody>
                <tr>
                    <td>Solde (cloture bande):</td>
                    <td>
                        <mark>
                            {{ soldeCloture }}
                            FCFA
                        </mark>
                    </td>
                </tr>
                <tr>
                    <td>Solde courant:</td>
                    <td>
                        <mark>
                            {{ soldeCurrent }}
                            FCFA
                        </mark>
                    </td>
                </tr>
                </tbody>
            </table>
        </figure>
    </article>
{% endblock %}

templates/bande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bande{% endblock %}

{% block body %}
    <article>
        <header>
            <h1>Créer une nouvelle bande</h1>
        </header>

        {{ include('bande/_form.html.twig') }}

        <footer><a href="{{ path('app_bande_index') }}">Retour à la liste des bandes</a></footer>
    </article>
{% endblock %}

templates/bande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bande
{% endblock %}

{% block body %}
    {% if bande.isClotured %}
        <h1>
            <del>Bande du
                {{ bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</del>
        </h1>
    {% else %}
        <h1>Bande du
            {{ bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</h1>
        <a href="#" data-target="modal-edit-bande" onclick="toggleModal(event)"
           data-tooltip="Editer les infos de la bande">
            <sub>
                <i class="fa-solid fa-pen-to-square"></i>
            </sub>
        </a>
    {% endif %}

    <table role="grid" class="table">
        <tbody>
        <tr>
            <th>Nombre de poussins</th>
            <td>{{ bande.nbPoussins }}</td>
        </tr>
        <tr>
            <th>Date démarrage</th>
            <td>{{ bande.dateDebut|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</td>
        </tr>
        <tr>
            <th>Durée (en jours)</th>
            <td>{{ bande.nbJours }}
                jours
            </td>
        </tr>
        <tr>
            <th>Mortalités</th>
            <td>{{ bande.nbMortalite }}</td>
        </tr>
        <tr>
            <th>Quantité en stock</th>
            <td>
                <mark>{{ stock }}</mark>
            </td>
        </tr>
        <tr>
            <th>Bilan</th>
            <td>
                <mark>
                    {{ bilan }}
                    FCFA
                </mark>
            </td>
        </tr>
        </tbody>
    </table>

    <details>
        <summary role="button" class="secondary">
            Dépenses
            {% if not bande.isClotured %}
                <a href="#" data-target="modal-add-depense" onclick="toggleModal(event)"
                   data-tooltip="Renseigner une dépense">
                    <i class="fa-solid fa-plus"></i>
                </a>
            {% endif %}
        </summary>

        <table role="grid" class="table">
            <tbody>
            <tr>
                <th>Description</th>
                <td>Prix</td>
                <td>Date</td>
                <td>Actions</td>
            </tr>
            {% for depense in bande.depenses %}
                <tr>
                    <th>{{ depense.description }}</th>
                    <td>{{ depense.prix }}
                        FCFA
                    </td>
                    <td>{{ depense.createdAt|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</td>
                    <td class="actions">
                        <a href="#" role="button" class="outline" data-tooltip="Consulter les details de la depense"
                           data-path-content="{{ path('app_depense_show', {'id': depense.id}) }}"
                           data-target="modal-detail-depense">
                            <i class="fa-regular fa-eye"></i>
                        </a>
                        <a href="#" `
                           data-path-content="{{ path('app_depense_edit', {'id': depense.id}) }}"
                           data-target="modal-edit-depense" role="button" class="outline"
                           data-tooltip="Modifier la depense">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        {{ include('depense/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th scope="col">Total</th>
                <td scope="col">
                    <mark>
                        {{ totalDepense }}
                        FCFA
                    </mark>
                </td>
            </tr>
            </tfoot>
        </table>
    </details>

    <details>
        <summary role="button" class="secondary">
            Ventes
            {% if not bande.isClotured %}
                <a href="#" data-target="modal-add-vente" onclick="toggleModal(event)"
                   data-tooltip="Renseigner une vente">
                    <i class="fa-solid fa-plus"></i>
                </a>
            {% endif %}
        </summary>
        <table role="grid" class="table">
            <tbody>
            <tr>
                <th>Nombre de poulets</th>
                <td>Prix</td>
                <td>Client</td>
                <td>Date</td>
                <td>Actions</td>
            </tr>
            {% for vente in bande.ventes %}
                <tr>
                    <th>{{ vente.quantite }}</th>
                    <td>{{ vente.prix }}
                        F CFA
                    </td>
                    <td>{{ vente.client }}</td>
                    <td>{{ vente.createdAt|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</td>
                    <td class="actions">
                        <a href="#" role="button" class="outline" data-tooltip="Consulter les details de la vente"
                           data-path-content="{{ path('app_vente_show', {'id': vente.id}) }}"
                           data-target="modal-detail-vente">
                            <i class="fa-regular fa-eye"></i>
                        </a>
                        <a href="#" data-path-content="{{ path('app_vente_edit', {'id': vente.id}) }}"
                           data-target="modal-edit-vente" role="button" class="outline"
                           data-tooltip="Modifier la vente">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        {{ include('vente/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th scope="col">Total</th>
                <td scope="col">
                    <mark>
                        {{ totalVente }}
                        FCFA
                    </mark>
                </td>
            </tr>
            </tfoot>
        </table>
    </details>
    <h2>Bilan:</h2>
    <mark>
        {{ bilan }}
        FCFA
    </mark>

    <!-- Modal -->
    <dialog id="modal-edit-bande">
        <article>
            <header>
                <a href="#close" aria-label="Close" class="close" data-target="modal-edit-bande"
                   onclick="toggleModal(event)"></a>
                <h3>Editer les infos de la bande!</h3>
            </header>
            {{ include('bande/_form.html.twig', {'button_label': 'Editer'}) }}
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-add-depense">
        <article>
            <header>
                <a href="#close" aria-label="Close" class="close" data-target="modal-add-depense"
                   onclick="toggleModal(event)"></a>
                <h3>Renseigner une nouvelle dépense!</h3>
            </header>
            {{ include('depense/_form.html.twig') }}
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-edit-depense">
        <article>
            <header>
                <a href="#close" aria-label="Close" class="close" data-target="modal-edit-depense"
                   onclick="toggleModal(event)"></a>
                <h3>Modifier la depense!</h3>
            </header>
            <div class="contentTarget"></div>
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-detail-depense">
        <article>
            <header>
                <h3>Details depense!</h3>
                <a href="#close" aria-label="Close" class="close" data-target="modal-detail-depense"
                   onclick="toggleModal(event)"></a>
            </header>
            <div class="contentTarget"></div>
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-add-vente">
        <article>
            <header><a href="#close" aria-label="Close" class="close" data-target="modal-add-vente"
                       onclick="toggleModal(event)"></a>
                <h3>Renseigner une nouvelle vente!</h3></header>
            {{ include('vente/_form.html.twig') }}
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-edit-vente">
        <article>
            <header>
                <a href="#close" aria-label="Close" class="close" data-target="modal-edit-vente"
                   onclick="toggleModal(event)"></a>
                <h3>Modifier la vente!</h3>
            </header>
            <div class="contentTarget"></div>
        </article>
    </dialog>

    <!-- Modal -->
    <dialog id="modal-detail-vente">
        <article>
            <header><a href="#close" aria-label="Close" class="close" data-target="modal-detail-vente"
                       onclick="toggleModal(event)"></a>
                <h3>Details vente!</h3></header>
            <div class="contentTarget"></div>
        </article>
    </dialog>
{% endblock %}